### PR TITLE
2022 01 26 madelein move surface holder update JDK and gradle versions

### PR DESCRIPTION
**Pull request by madeleinvillegas**
# PR Info

## Issue Details

 - **Fixes** #---- 
 - **Addresses** #---- 

## Branch
 - **Addresses** `development` 

## Type of change

- **Bug Fix** 
- **New Feature** 
- **Breaking Change** 
- **Other**

### CODE REVIEW

**Review by JackMostow — COMMENTED** [review]
In app/build.gradle:
"./../../../../../build/" makes a strong and hence risky assumption about where the apk will run.:
            def newApkName = project + SEP + buildType + SEP + version + ".apk"
            outputFileName = new File("./../../../../../build/", newApkName) 
If it's not feasible to eliminate the assumption, at least document the specific assumed usual location in a comment

Why is this line duplicated?
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'

Was there any reason to move this line?
zipStoreBase=GRADLE_USER_HOME

**Comment by madeleinvillegas** [comment]
@sushant-varanasi @JackMostow Hi Sushant! I need help enabling the Travis code to automatically compile an apk. I can't see a new apk generated even if I followed the directions on the pull request so I don't think I have it enabled.

**Review by JackMostow — COMMENTED** [review]
Looks good; is it ready to approve?

**Review by JackMostow — CHANGES_REQUESTED** [review]
I assume before I approve this request I should wait for the conflicts to be resolved.

**Comment by sushant-varanasi** [comment]
> @sushant-varanasi @JackMostow Hi Sushant! I need help enabling the Travis code to automatically compile an apk. I can't see a new apk generated even if I followed the directions on the pull request so I don't think I have it enabled.

Yeah, there is an issue regarding apk generation by Travis. It hasn't been fixed yet and so no APK gets generated as of now in this repository.

**Comment by JackMostow** [comment]
Madelein and Rohan fixed conflicts, so Jack merged and deleted 2022-01-26-Madelein-Move-Surface-Holder branch.

**Pull request merged**
