### PR TITLE
Add automatic apk generation using travis

### PR DESCRIPTION
**Pull request by sansyrox**
Add automatic apk genration using travis

### CODE REVIEW

**Review by JackMostow — DISMISSED** [review]
Let's hope this works since I don't really understand the code.

**Review by JackMostow — DISMISSED** [review]

**Comment by JackMostow** [comment]
@sushant-varanasi - Please fix the conflicts to enable automatic apk generation.
For now, Rohan is manually uploading his apk to the apk branch as a 1-time workaround.

**Review by JackMostow — CHANGES_REQUESTED** [review]
@sushant-varanasi -
1. Will this change make automatic apk generation work, or is it obsoleted by a later change?
2. Please resolve conflicts so I can approve the change if consistent with answer to  #1 above.

**Comment by sushant-varanasi** [comment]
> @sushant-varanasi -
> 
> 1. Will this change make automatic apk generation work, or is it obsoleted by a later change?
> 2. Please resolve conflicts so I can approve the change if consistent with answer to  #1 above.

Sir,
1. Mostly obsoleted by later changes, but there are some small differences.
2. I am resolving differences accordingly.

Also, I have a query - Should the new apk be generated in this repository or in the main robotutor repository?

**Comment by JackMostow** [comment]
@sushant-varanasi - Please generate new apks for RTFaceLogin in [https://github.com/RoboTutorLLC/RTFace_Login/tree/apk](https://github.com/RoboTutorLLC/RTFace_Login/tree/apk).

**Pull request merged**
