### PR TITLE
2023 01 02 madelein logging state changes

### PR DESCRIPTION
**Pull request by madeleinvillegas**

### CODE REVIEW

**Review by JackMostow — COMMENTED** [review]
public void onCompletion(MediaPlayer mp) {
                                                logHandler.log(Pair.create("student_tapped_finish", icntext));
Does onCompletion get called only when student taps?  What if recording finishes playing?

**Review by JackMostow — COMMENTED** [review]
P.S. @madelein - The log should be a sequence of JSON expressions, one per event, not a single overall JSON expression as in your example, because it won't be legal JSON if FaceLogin crashes before adding a terminator.

**Comment by madeleinvillegas** [comment]
Unfortunately, just a sequence of JSON expressions is not legal JSON. I tried it out and I was getting parsing errors when trying to parse the resulting log file. The sequence must be encapsulated in a JSON array or object. 

The log is updated every event to add the new event and to ensure legal JSON. In a sense, I am appending the file every event. When FaceLogin crashes, the log before the crash (which is already) legal should be saved if the crash does not survive adding the new event. I will try to simulate a crash once I get home from school.

**Comment by JackMostow** [comment]
What you describe is what RoboTutor already does, including a {"end":"end"} terminator.  I don't recall why -- perhaps as an easy way to tell a log is incomplete if it's missing.

Yes, a sequence of JSON objects is not legal JSON.  I was hoping there's an existing function to load a sequence of JSON objects, but Dr. Google appears to suggest otherwise (see "parsing muliple objects").

So keep what you have.  But to remain legal JSON, it has to delete the previous terminator each time it logs another event.

**Comment by madeleinvillegas** [comment]
Created a new branch and pull request with a working code

**Pull request closed without merging**
