### PR TITLE
Upgraded gradle version

### PR DESCRIPTION
**Pull request by sushant-varanasi**
@JackMostow Before starting to integrate Travis in this repository, I tried building RTFace_Login in my local system.
It threw errors, and on analysing, I inferred that it had been due to depreciated Gradle version. 
So, I updated the Gradle version(some following changes were to be made, not just incrementing the number) and tested it on my system - The app builds properly with no issues.

Now after this PR gets merged, I shall start integrating Travis into this repository.

Thanks,
Sushant

### CODE REVIEW

**Review by JackMostow — APPROVED** [review]

**Comment by JackMostow** [comment]
I assume you know what you're doing, so I'll go ahead and merge.

**Comment by JackMostow** [comment]
I tried to merge, but the branch included unmerged commits, so I reopened the PR.

**Comment by sushant-varanasi** [comment]
> "outputFileName = new File("./../../../../../build/", newApkName)" makes a strong assumption about folder structure. At minimum document the assumed structure.

This was suggested by a StackOverflow answer

> Does upgrading the Gradle version also fix the RoboFeel python issue?

It shouldn't be, logically. I'll give it a try if you want me to though.

**Comment by sushant-varanasi** [comment]
> I tried to merge, but the branch included unmerged commits, so I reopened the PR.

The branch had been up-to-date until I pushed 1 commit. I'm not sure what the problem is.

**Comment by JackMostow** [comment]
When I try to merge pull request, it says "Add more commits by pushing to the gradle-update branch on RoboTutorLLC/RTFace_Login."  Does that mean I shouldn't proceed with the merge?

**Comment by sushant-varanasi** [comment]
> When I try to merge pull request, it says "Add more commits by pushing to the gradle-update branch on RoboTutorLLC/RTFace_Login." Does that mean I shouldn't proceed with the merge?

If you can proceed with the merge, I think you should proceed.
It doesn't mean to stop.

**Comment by JackMostow** [comment]
Done.  Let me know if it does what you need, and if the same change fixes the python issue in RoboFeel (if it's quick to check).
Thanks! - Jack

**Pull request merged**
