### PR TITLE
Workflow added for APK generation

### PR DESCRIPTION
**Pull request by gargVader**
Github Actions workflow added for auto generation of APK whenever a commit is pushed.
In order to access the APK:
- Click on `Checks` in Pull Request
- Click on `Pre Merge Checks`
- Find the APK in artifacts

### CODE REVIEW

**Comment by JackMostow** [comment]
@gargVader - Girish, is this you, or an automated version of yourself?
The checks have failed, so I won't approve commits yet.
Bhuvan, Bhargav, and I were just working on some of the same files in the 2022-11-17-video-launch-corruption-fix and are about to push their changes to it, so beware of possible conflicts.  But it would be great if you can make auto-apk generation work for RTFaceLogin!  Thanks. - Jack

**Comment by gargVader** [comment]
@JackMostow This will auto-generate APK whenever a commit is made. The code is good to merge if you want.

I believe that uploading the apk to artifacts is the standard way of doing it as I haven't seen any other method in my experience. I think this is simple and should suffice, rather than putting the apk in a separate branch. What do you think?

**Comment by JackMostow** [comment]
Girish - Madelein and I are trying out your auto-generated apk and I just
noticed an 11/25/2022 email from you, which I assume you sent to my Gmail
account, which I don't read email on.  Although I use Gmail to read email,
the only email account I use is ***@***.***, which gets routed to
***@***.***  So please use it in future, not
***@***.***  Thanks!  - Jack

**Review by JackMostow — APPROVED** [review]
Madelein vouches for the auto-generation working ;-), so I'll approve and merge into development.

**Review by madeleinvillegas — APPROVED** [review]
I hope this works :')

**Comment by JackMostow** [comment]
At last!

**Pull request merged**
