### PR TITLE
2022 11 17 video launch corruption fix

### PR DESCRIPTION
**Pull request by madeleinvillegas**

### CODE REVIEW

**Comment by JackMostow** [comment]
@madeleinvillegas - I started to review pull request https://github.com/RoboTutorLLC/RTFace_Login/pull/34 for 2022 11 17 video launch corruption fix.  However, you closed it around noon 11/21/2022 "but the 2022-11-17-video-launch-corruption-fix branch has unmerged commits."  Except for changing versions of jdk and build.gradle, all the merges were merging the development branch into apk_generation, so I'm guessing it was a mistake and that's why you closed the PR.

The 2022-11-17-video-launch-corruption-fix branch is [10 commits ahead](https://github.com/RoboTutorLLC/RTFace_Login/compare/development...2022-11-17-video-launch-corruption-fix), [1 commit behind](https://github.com/RoboTutorLLC/RTFace_Login/compare/2022-11-17-video-launch-corruption-fix...development) development.  Is it ready to merge into development?  I assume not yet, or you would have made a pull request to do so.

Please advise.  Thanks!  - Jack

**Comment by madeleinvillegas** [comment]
Yes, it was a mistake. I thought @rohankulkz  pushed his changes regarding the media player, so I opened a pull request. I closed it after realizing the push did not happen.

**Comment by JackMostow** [comment]
@madeleinvillegas -- So the next steps are:
1. Rohan push his changes to the 2022-11-17-video-launch-corruption-fix branch.  He just did (12/1/2022).
2. Merge development into it, but it's not ready yet.

**Review by JackMostow — APPROVED** [review]
Looks good as far as I can tell, which isn't very ;-).
Someday still want to replace tangled code with simple 2-line query.

**Comment by JackMostow** [comment]
We weren't sure which type of merge to use, so we tried rebase but it failed.  We used merge commit for fear that squash commit would be hard to untangle if it fails.

**Pull request merged**
