### PR TITLE
2023 02 16 rishideep dump & load user profile

### PR DESCRIPTION
**Pull request by rishideepc**
* Updated onUpgrade() method - added user profile backup before dropping table

* Updated onCreate() method - checks presence of backup, if found - copies the data to new table created, else - simply creates the new table

### CODE REVIEW

**Review by JackMostow — CHANGES_REQUESTED** [review]
eliminate replicated code e.g. by factoring

**Review by JackMostow — CHANGES_REQUESTED** [review]
Need to dump db to file and load db from file.
When?

**Review by JackMostow — CHANGES_REQUESTED** [review]
See [2023-03-02 Rishideep Meeting 4 Notes](https://docs.google.com/document/d/1cSm3wKkl2yVY4wIqVsFUqRCOuBFaG479bhE6RBmL6zs/edit) about keeping old dumps and retrieving only the latest

**Comment by JackMostow** [comment]
@rishideepc - Which of these two should we keep in order to resolve the conflict?  - Jack

<<<<<<< 2023-02-15-Rishideep-Dump-And-Load-RTFaceLogin-User-Profiles
  <component name="ProjectRootManager" version="2" languageLevel="JDK_18" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
=======
  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" project-jdk-name="1.8" project-jdk-type="JavaSDK">
>>>>>>> development

**Comment by rishideepc** [comment]
> @JackMostow Sir, I believe we should keep the development branch version, it seems compatible with the original repo. I have resolved the conflict and pushed the code. I have also made the necessary changes to restore the lastModified JSON from the dump directory, as discussed in the last meeting.
Thanks - Rishideep!

**Review by JackMostow — APPROVED** [review]
Looks fine, though restoreUserProfiles could use a comment to explain that it restores the db from the most recent dump according to its timestamp, which we assume was not afflicted by the clock reset problem.

**Review by JackMostow — APPROVED** [review]

**Comment by JackMostow** [comment]
I'm going ahead with the squash and merge, but please confirm that the resulting apk works OK.  Thanks!  - Jack

**Pull request merged**
